apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-amf
  labels:
    app.kubernetes.io/name: amf
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: amf
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: sbi
      port: 7778
      targetPort: sbi
      protocol: TCP
    - name: metrics
      port: 9465
      targetPort: metrics
      protocol: TCP
