apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-smf
  labels:
    app.kubernetes.io/name: smf
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: smf
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: sbi
      port: 7779
      targetPort: sbi
      protocol: TCP
    - name: metrics
      port: 9466
      targetPort: metrics
      protocol: TCP
