#pragma once

#include <cstdint>
#include <optional>
#include <vector>

// PFCP (Packet Forwarding Control Protocol, N4/Sx reference points) message header codec --
// TS 29.244 §7.1/§7.2.2. PFCP has no OpenAPI YAML (it's a binary UDP protocol, port 8805, not an
// SBI/HTTP2 API), so unlike every other NF's codec in this project, this is hand-rolled from the
// real spec text rather than generated by tools/sbi-codegen -- same class of exception NAS-5GS's
// codec already established (nfs/amf/src/nas_codec.hpp), for the same reason (no machine-readable
// schema exists for this protocol family).
//
// Byte layouts below were read directly from the real, official 3GPP TS 29.244 V14.3.0 (2018-03)
// specification PDF (fetched from the ARIB archive mirror, a genuine 3GPP Organizational Partner
// publication site, and read via this project's PDF-reading tooling -- not from memory, not
// fabricated), clause 7.2.2 "Message Header" and Table 7.3-1 "Message Types". Vendored at
// specs/PFCP/29244-e30.pdf for reproducibility. Disclosed version
// gap: V14.3.0 is the release that was actually available to verify against, not this project's
// REL-19 baseline -- the core PFCP header/TLV format has been stable since PFCP's Release 14
// introduction (CUPS) and no later-release change to clause 7.2.2 itself is known, but this is a
// disclosed assumption, not a REL-19-text-verified fact, flagged here rather than silently
// presented as REL-19-sourced. See docs/DECISIONS.md ADR-0039.

namespace pfcp_core {

constexpr std::uint8_t kPfcpVersion = 1;
constexpr std::uint16_t kPfcpPort = 8805; // TS 29.244 §4.2.1, IANA-assigned

// NOT an IANA/spec-assigned value -- the CP function's own PFCP listening port has no such
// assignment in the real spec (real deployments convey it out-of-band, e.g. DNS/configuration,
// same as this project's own hardcoded-per-NF-port convention for every SBI/HTTP port already).
// Needed starting with ADR-0049's quota-consumption-tracking turn: UPF must be able to reach SMF
// directly for an unsolicited Sx Session Report Request, which real per-call ephemeral sockets
// (this project's earlier PFCP work) could never receive. Shared here (not private to one NF)
// because both smf (binds it) and upf (sends to it) need to agree on the same value.
constexpr std::uint16_t kSmfCpFunctionPfcpPort = 8806;

enum class MessageType : std::uint8_t {
    HeartbeatRequest = 1,
    HeartbeatResponse = 2,
    AssociationSetupRequest = 5,
    AssociationSetupResponse = 6,
    AssociationReleaseRequest = 9,
    AssociationReleaseResponse = 10,
    SessionEstablishmentRequest = 50,
    SessionEstablishmentResponse = 51,
    SessionModificationRequest = 52,
    SessionModificationResponse = 53,
    SessionDeletionRequest = 54,
    SessionDeletionResponse = 55,
    SessionReportRequest = 56,
    SessionReportResponse = 57,
};

// TS 29.244 §7.2.2.2 (node-related, S=0, 8-byte header) / §7.2.2.3 (session-related, S=1,
// 16-byte header). This project's Stage 1 only uses node-related messages (Heartbeat, Association
// Setup) -- has_seid/seid exist now so the session-related form doesn't need a second struct once
// Stage 3 adds Session Establishment.
struct Header {
    bool has_seid = false; // the "S" flag, octet 1 bit 1
    MessageType message_type = MessageType::HeartbeatRequest;
    std::uint64_t seid = 0; // valid iff has_seid; octets 5-12 when present
    // 24-bit value (octets 5-7 for node-related, 13-15 for session-related) -- stored in the low
    // 24 bits, high byte always 0.
    std::uint32_t sequence_number = 0;
};

// Encodes the header only (8 or 16 bytes depending on has_seid) with message_length already
// filled in -- callers encode their IEs first, then call this with the resulting IE byte count
// (TS 29.244 §7.2.2.1: Message Length excludes the mandatory first 4 octets of the header itself,
// but INCLUDES the SEID/Sequence Number/spare octets that follow when present).
std::vector<std::uint8_t> encode_header(const Header& header, std::uint16_t ies_length);

// Decodes a header from the start of `bytes`. On success, advances `offset` past the header (so
// the caller can decode IEs starting at `offset`) and sets `ies_length` to the number of IE bytes
// that follow (the wire Message Length field minus the seq/spare/SEID overhead already consumed
// into `offset` -- the same quantity encode_header's `ies_length` parameter takes, so callers
// never need to do this arithmetic themselves). Returns std::nullopt on a too-short buffer,
// unrecognized version, or a Message Length field too small to even cover the fixed overhead.
std::optional<Header> decode_header(const std::vector<std::uint8_t>& bytes, std::size_t& offset,
                                    std::uint16_t& ies_length);

} // namespace pfcp_core
