apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nrf
  labels:
    app.kubernetes.io/name: nrf
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: nrf
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: sbi
      port: 7777
      targetPort: sbi
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: metrics
      protocol: TCP
